Controllers/BrandController.cs
using InventoryManagement.Data;
using InventoryManagement.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryManagement.Controllers
{
    public class BrandController : Controller
    {
        private readonly MyDbContext context;

        public BrandController(MyDbContext _context)
        {
            context = _context;

        }


        // GET: BrandController
        public ActionResult Index()
        {
            var objList = context.Brands.ToList();
            ViewBag.BrandList = objList;
            return View();
        }

        // GET: BrandController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: BrandController/Create
        public ActionResult Create()
        {

            return View();
        }

        // POST: BrandController/Create
        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            if (ModelState.IsValid)
            {
                
                context.Brands.Add(brand);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return Json(new { istrue = false, message = "Failed" });
            }
            return Json(new { istrue = true, message = "Saved" });
        }

        // GET: BrandController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: BrandController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: BrandController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: BrandController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/CategoryController.cs
using InventoryManagement.Data;
using InventoryManagement.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryManagement.Controllers
{
    public class CategoryController : Controller
    {
        private readonly MyDbContext context;

        public CategoryController(MyDbContext _context)
        {
            context = _context;

        }
        public IActionResult Index()
        {

            //List<Category> categoryList = context.Categories.ToList();

            var objList = context.Categories.ToList();


            //objList.Add(new Category() { CategoryId = 1 , Name = "Food"});
            //objList.Add(new Category() { CategoryId = 2 , Name = "Food"});
            //objList.Add(new Category() { CategoryId = 3 , Name = "Food"});



            ViewBag.CategoryList = objList;

            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.CategoryList = context.Categories.ToList();

            return View();
        }
        [HttpPost]
        public IActionResult Create(Category model)
        {
            Category objList = new Category() { Name = model.Name};

            Brand objbrand = new Brand();

            context.Categories.Add(objList);
            context.Brands.Add(objbrand);
            context.SaveChanges();
            
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            //Find Data from database based on id asp-route-id="@item.CategoryId"
            var category = context.Categories.Where(x => x.CategoryId == id).FirstOrDefault();

            return View(category);


            //return View(category);
        }

        [HttpPost]
        public IActionResult Edit(Category model)
        {
            Category obj = new Category() { CategoryId = model.CategoryId, Name = model.Name };
            context.Categories.Update(obj);
            context.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
           var data = context.Categories.Find(id);

            return View(data);
        }
        [HttpPost]
        public IActionResult Delete(Category category)
        {
            var data = context.Categories.Find(category.CategoryId);
            context.Categories.Remove(data);
            context.SaveChanges();
            return View();
        }

        //[HttpPost]
        //public IActionResult Edit(int CategoryId, string Name)
        //{
        //    Category obj = new Category() {CategoryId= CategoryId, Name = Name };
        //    context.Categories.Update(obj);
        //    context.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //public JsonResult GetCategorys()
        //{
        //    var objList = context.Categories.ToList();
        //    return Json(objList);

        //}

    }
}

Controllers/ProductController.cs
using InventoryManagement.Data;
using InventoryManagement.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InventoryManagement.Controllers
{
    public class ProductController : Controller
    {

        private readonly MyDbContext context;

        public ProductController(MyDbContext _context)
        {
            context = _context;

        }

        public IActionResult Index()
        {
            ViewBag.CategoryList = new SelectList(context.Categories.ToList(), "CategoryId", "Name");

            ViewBag.BrandList = new SelectList(context.Brands.ToList(), "BrandId", "Name");

            var obj = context.Products.Include(g => g.Category).Include(g=>g.Brand).DefaultIfEmpty().ToList();
           // var objbrand = context.Brands.Include(g => g.BrandId).DefaultIfEmpty().ToList();
            return View(obj);

            //List<Product> objList = context.Products.ToList();
            //return View(objList);
        }
        [HttpGet]
        public IActionResult Create()
        {
            //var list = new SelectList(context.Categories.ToList(), "CategoryId", "Name");
            //ViewBag.CategoryList = list;
            var catList = context.Categories.ToList();
            ViewBag.CategoryList = catList;

            var brandlist = context.Brands.ToList();
            ViewBag.BrandList = brandlist;



            return View();
        }
        [HttpPost]
        public IActionResult Create(Product model)
        {
            if (ModelState.IsValid)
            {
                context.Products.Add(model);
                context.SaveChanges();
            }
            else
            {
                return Json(new { istrue = false, message = "Failed" });
            }
            return Json(new { istrue = true, message = "Saved" });
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {

            
            ViewBag.CategoryList = new SelectList(context.Categories.ToList(), "CategoryId", "Name");
            ViewBag.BrandList = new SelectList(context.Brands.ToList(), "BrandId", "Name");
            var obj = context.Products.Find(id);


            return View(obj);

        }

        [HttpPost]
        public IActionResult Edit(Product product)
        {

            //var data = context.Products.Find(product.ProductId);

            var obj = context.Products.Update(product);

            context.SaveChanges();
            return View(obj);

        }


        [HttpPost]

        public IActionResult Delete(Product product)
        {
            
            var data = context.Products.Find(product.ProductId);

            var obj = context.Products.Remove(data);

            context.SaveChanges();
            return View(obj);

        }


        [HttpGet]
        public IActionResult DeleteProduct(int id)
        {
            ViewBag.CategoryList = new SelectList(context.Categories.ToList(), "CategoryId", "Name");

            ViewBag.BrandList = new SelectList(context.Brands.ToList(), "BrandId", "Name");
            var obj = context.Products.Find(id);
            return View(obj);

        }


        [HttpGet]
        public JsonResult AdvanceSearchViewModal(int BrandId, int CategoryId)
        {

            var query = context.Products.Include(g => g.Brand).Include(g => g.Category).DefaultIfEmpty();
            ///IQUERABLE
            if (BrandId != -1)
            {
                query = query.Where(w => w.BrandId == BrandId);
            }
            if (CategoryId != -1)
            {
                query = query.Where(w => w.CategoryId == CategoryId);
            }

           /* select productid as prodid from product   */
          
            return Json(new { data = query.Select(s=> new {s.ProductId,brandname=s.Brand.Name,s.Name,s.Qty,s.SalePrice,categoryname=s.Category.Name }).ToList() });
        }


    }
}

Controllers/ReportController.cs
using AspNetCore.Reporting;
using InventoryManagement.Data;
using InventoryManagement.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace InventoryManagement.Controllers
{

    public class ReportController : Controller
    {
        private readonly MyDbContext context;
        private readonly IWebHostEnvironment webHostEnviroment;

        public ReportController(MyDbContext _context , IWebHostEnvironment _webHostEnviroment)
        {
            context = _context;

            webHostEnviroment = _webHostEnviroment;

        }

        public IActionResult Index()
        {
            return View();
        }

        public byte[] GenerateReportsAsync()
        {
            //string fileDirPath = Assembly.GetExecutingAssembly().Location.Replace("ReportAPI.dll", string.Empty);
            string rdlcFilePath = webHostEnviroment.WebRootPath + string.Format("\\{0}\\{1}.rdlc", "RDLCReport", "Report3");
            Dictionary<string, string> parameters = new Dictionary<string, string>();
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            Encoding.GetEncoding("windows-1252");
            LocalReport report = new LocalReport(rdlcFilePath);

            //List<Product> productList = new List<Product>();
            //productList = context.Products.ToList();
            // Start_Time = 10
            //End_time = 16
            //subtract = End_time - Start_Time = 6

            //var subtract = ltask.Where(x => x.End_Time - x.Start_Time);

            //.Contains("76")



//            select PRODUCTS.ProductId AS ID,
// MAX(Products.[Name]) as Product
//,MAX(Brands.[Name]) as Brand
//,MAX(Categories.[Name]) as Category
//,MAX(Products.SalePrice) as Price
//,MAX(Products.Qty) as TotalQty

//, Count(Allotments.ProductId) AS TotalSold

//from Products
//left join Allotments on Products.ProductId = Allotments.ProductId
//left
//join Brands on Products.BrandId = Brands.BrandId
//left
//join Categories on Products.CategoryId = Categories.CategoryId


//GROUP BY Products.ProductId
//ORDER BY Products.ProductId






       var dataaa = context.Products.AsNoTracking()
                .Include(g => g.Allotments).DefaultIfEmpty()
                .Include(g => g.Brand)
                .Include(g => g.Category)
                .Select(s => new
                {
                    ProductName = s.Name,
                    Brand = s.Brand.Name,
                    CategoryName = s.Category.Name,
                    SalePrice = s.SalePrice,
                    TotalQty = s.Qty,
                    TottalSold = s.Allotments.Where(w=>w.ProductId==s.ProductId).Count()
                }).ToList();

            var dataList = context.Allotments.Include(g => g.Customer).Include(g => g.Product).DefaultIfEmpty().Where(g=>g.CustomerId==3).Select(s => new { s.AllotmentId, createddate = s.CreatedDate.ToString("dd-MMM-yyyy"), s.ProductId, productname = s.Product.Name,s.CustomerId, customername = s.Customer.CustomerName}).ToList();


            //var qry1 = context.Allotments.Include(f => f.Product).DefaultIfEmpty().Select(s => new { s.ProductId, s.CustomerId, productid = s.Product.ProductId }).ToList();

            //var qry = context.Products.ToList();
            

            string totalproduct = context.Allotments.Count().ToString();




            // var obj = context.Products.Include(g => g.Category).Include(g => g.Brand).DefaultIfEmpty().ToList();


            //var dataList = context.Products.Include(g => g.Brand).Include(g => g.Category).DefaultIfEmpty().Where(g=>g.Qty==76 || g.Name=="Food1").Select(s => new { s.ProductId, brandname = s.Brand.Name, s.Name, s.Qty, s.SalePrice, categoryname = s.Category.Name }).ToList();




            List <Category> categoryList = new List<Category>();
            categoryList = context.Categories.ToList();


            

            report.AddDataSource("DataSet3", dataaa);
            var result = report.Execute(GetRenderType("pdf"), 1, parameters);
            return result.MainStream;
        }

        private RenderType GetRenderType(string reportType)
        {
            var renderType = RenderType.Pdf;
            switch (reportType.ToLower())
            {
                default:
                case "pdf":
                    renderType = RenderType.Pdf;
                    break;
                case "word":
                    renderType = RenderType.Word;
                    break;
                case "excel":
                    renderType = RenderType.Excel;
                    break;
            }

            return renderType;
        }

     
        public ActionResult GetReport()
        {
            var returnString = GenerateReportsAsync();
            return File(returnString, System.Net.Mime.MediaTypeNames.Application.Octet, "fahad" + ".pdf");
        }

    }
}

Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">


    <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css" />
    <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css" />


    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">

</head>
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light m-0">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" @*data-widget="pushmenu"*@ href="~/Home/Index" role="button">@*<i class="fas fa-bars"></i>*@<i class="fa fa-home"></i></a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a asp-action="Index" asp-controller="Product" class="nav-link">Add Product</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-action="Index" asp-controller="Category">Category List</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-action="Index" asp-controller="Brand">Brand List</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-action="GetReport" asp-controller="Report" target="_blank">Generate Report</a>
                </li>
            </ul>

        </nav>

    </div>

    <!--<div class="container">
        <div class="row">
            <div class="col-lg-3 col-6">-->
                <!-- small box -->
                <!--<div class="small-box bg-info">
                    <div class="inner">
                        <h3>150</h3>

                        <p>New Orders</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>-->
            <!-- ./col -->
            <!--<div class="col-lg-3 col-6">-->
                <!-- small box -->
                <!--<div class="small-box bg-success">
                    <div class="inner">
                        <h3>53<sup style="font-size: 20px">%</sup></h3>

                        <p>Bounce Rate</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>-->
            <!-- ./col -->
            <!--<div class="col-lg-3 col-6">-->
                <!-- small box -->
                <!--<div class="small-box bg-warning">
                    <div class="inner">
                        <h3>44</h3>

                        <p>User Registrations</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-person-add"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>-->
            <!-- ./col -->
            <!--<div class="col-lg-3 col-6">-->
                <!-- small box -->
                <!--<div class="small-box bg-danger">
                    <div class="inner">
                        <h3>65</h3>

                        <p>Unique Visitors</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-pie-graph"></i>
                    </div>
                    <a href="#" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
                </div>
            </div>-->
            <!-- ./col -->
        <!--</div>
    </div>-->



    @RenderBody()

    <style>
        .HideLoader {
            display: none;
        }

        .ShowLoader {
            display: normal;
        }
    </style>


    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>

    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>



    <!--My Ajax links -->
    <script src="~/jquery/jquery.unobtrusive-ajax.js"></script>
    <script src="~/jquery/jquery.unobtrusive-ajax.min.js"></script>

    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!--DataTables-->

    @*<script src="~/plugins/datatables/jquery.dataTables.min.js"></script>*@
    <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    @*<script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>*@
    <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/plugins/jszip/jszip.min.js"></script>
    <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>

    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>
    <script src="~/dist/js/adminlte.min.js"></script>
    @*<script srhttps://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js"></script>*@
    <!-- AdminLTE for demo purposes -->
    @*<script src="dist/js/demo.js"></script>*@
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>


    <script>
        function onAjaxBegin() {
            alert();
            $("#divLoading").removeClass("ShowLoader").addClass("ShowLoader");
        }

        function onAjaxComplete(data) {
            alert();
            if (data.istrue) {
                alert(data.message);
            }
            else {
                alert("Failed")
            }

            $("#divLoading").removeClass("ShowLoader").addClass("HideLoader");
        }
    </script>

</body>
</html>

@RenderSection("Scripts", required: false)